"""empty message

Revision ID: 00d18f14e876
Revises: 
Create Date: 2021-08-07 10:20:19.380209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d18f14e876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('journal_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_month', sa.Integer(), nullable=False),
    sa.Column('journal_day', sa.Integer(), nullable=False),
    sa.Column('journal_title', sa.String(), nullable=False),
    sa.Column('journal_text', sa.String(), nullable=False),
    sa.Column('journal_mood', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('journal_entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
