"""empty message

Revision ID: 6e5adaae5f20
Revises: 
Create Date: 2021-07-29 16:49:41.347961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5adaae5f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_entry',
    sa.Column('dream_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dream_date', sa.DateTime(), nullable=True),
    sa.Column('dream_title', sa.String(), nullable=True),
    sa.Column('dream_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dream_entry_id')
    )
    op.drop_table('journal_entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('dream_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dream_name', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('dream_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dream_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dream_entry_id', name='journal_entries_pkey')
    )
    op.drop_table('dream_entry')
    # ### end Alembic commands ###
