"""empty message

Revision ID: 826f58c4631b
Revises: 
Create Date: 2021-08-14 09:14:54.121962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826f58c4631b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('journal_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('journal_text', sa.String(), nullable=False),
    sa.Column('journal_mood', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('journal_entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
