"""empty message

Revision ID: e0290a7e9c62
Revises: 
Create Date: 2021-08-06 14:18:45.428631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0290a7e9c62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('journal_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_date', sa.String(), nullable=True),
    sa.Column('journal_title', sa.String(), nullable=True),
    sa.Column('journal_text', sa.String(), nullable=True),
    sa.Column('journal_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('journal_entry_id')
    )
    op.create_table('journal_tag',
    sa.Column('journal_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_tag', sa.String(), nullable=True),
    sa.Column('journal_tag_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('journal_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_tag')
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
