"""empty message

Revision ID: eaa6320445ec
Revises: 
Create Date: 2021-08-06 12:21:30.536677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa6320445ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry',
    sa.Column('journal_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_date', sa.String(), nullable=True),
    sa.Column('journal_title', sa.String(), nullable=True),
    sa.Column('journal_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('journal_entry_id')
    )
    op.create_table('journal_tag',
    sa.Column('journal_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_tag', sa.String(), nullable=True),
    sa.Column('journal_tag_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('journal_tag_id')
    )
    op.create_table('mood_entry',
    sa.Column('mood_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mood_entry', sa.String(), nullable=True),
    sa.Column('mood_entry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mood_entry_id')
    )
    op.create_table('mood_tag',
    sa.Column('mood_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mood_tag', sa.String(), nullable=True),
    sa.Column('mood_tag_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mood_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_tag')
    op.drop_table('mood_entry')
    op.drop_table('journal_tag')
    op.drop_table('journal_entry')
    # ### end Alembic commands ###
